apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-operator.fullname" . }}-authprovider-secrets
  labels:
  {{- include "auth-operator.labels" . | nindent 4 }}
data:
  API_TOKEN: {{ required "authproviderSecrets.apiToken is required" .Values.authproviderSecrets.apiToken
    | b64enc | quote }}
  API_TOKEN_REFRESH: {{ required "authproviderSecrets.apiTokenRefresh is required"
    .Values.authproviderSecrets.apiTokenRefresh | b64enc | quote }}
  API_TOKEN_REFRESH_URL: {{ required "authproviderSecrets.apiTokenRefreshUrl is required"
    .Values.authproviderSecrets.apiTokenRefreshUrl | b64enc | quote }}
  IDP_URL: {{ required "authproviderSecrets.idpUrl is required" .Values.authproviderSecrets.idpUrl
    | b64enc | quote }}
