apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "auth-operator.fullname" . }}-binder-validating-webhook-configuration
  labels:
  {{- include "auth-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "auth-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-authorization-t-caas-telekom-com-v1alpha1-binddefinition
  failurePolicy: Fail
  name: binder.validating.webhook.auth.t-caas.telekom.de
  rules:
  - apiGroups:
    - authorization.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - binddefinitions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "auth-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-authorization-t-caas-telekom-com-v1alpha1-roledefinition
  failurePolicy: Fail
  name: roledefinition.validating.webhook.auth.t-caas.telekom.de
  rules:
  - apiGroups:
    - authorization.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - roledefinitions
  sideEffects: None
