{{- if .Values.controller.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "auth-operator.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "auth-operator.labels" . | nindent 4 }}
spec:
  {{- if and .Values.controller.podDisruptionBudget.minAvailable .Values.controller.podDisruptionBudget.maxUnavailable }}
  {{- fail "podDisruptionBudget.minAvailable and podDisruptionBudget.maxUnavailable are mutually exclusive" }}
  {{- else if .Values.controller.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.controller.podDisruptionBudget.minAvailable }}
  {{- else if .Values.controller.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.controller.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "auth-operator.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.webhookServer.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "auth-operator.fullname" . }}-webhook-server
  labels:
    control-plane: webhook-server
  {{- include "auth-operator.labels" . | nindent 4 }}
spec:
  {{- if and .Values.webhookServer.podDisruptionBudget.minAvailable .Values.webhookServer.podDisruptionBudget.maxUnavailable }}
  {{- fail "podDisruptionBudget.minAvailable and podDisruptionBudget.maxUnavailable are mutually exclusive" }}
  {{- else if .Values.webhookServer.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.webhookServer.podDisruptionBudget.minAvailable }}
  {{- else if .Values.webhookServer.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.webhookServer.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      control-plane: webhook-server
    {{- include "auth-operator.selectorLabels" . | nindent 6 }}
{{- end }}
