apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auth-operator.fullname" . }}
  labels:
  {{- include "auth-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
