apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auth-operator.fullname" . }}
  labels:
  {{- include "auth-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
