apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "auth-operator.fullname" . }}-webhook-server-clusterrolebinding
  labels:
  {{- include "auth-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "auth-operator.fullname" . }}-webhook-server-clusterrole'
subjects:
- kind: ServiceAccount
  name: '{{ include "auth-operator.fullname" . }}-webhook-server'
  namespace: '{{ .Release.Namespace }}'
