apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-operator.fullname" . }}-webhook-service
  labels:
    authorization.t-caas.telekom.com/component: webhook
  {{- include "auth-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
    {{- include "auth-operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}