apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds/authprovider-crd.yaml
- crds/binddefinition-crd.yaml
- crds/roledefinition-crd.yaml
- crds/webhookauthorizer-crd.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: Delete=false
  helm.sh/resource-policy: keep
