{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "t-caas-rbac-generator.fullname" . }}
  labels:
{{ include "t-caas-rbac-generator.labels.standard" . | indent 4 }}
subjects:
{{- if .Values.serviceAccount.create }}
  - kind: ServiceAccount
    name: {{ template "t-caas-rbac-generator.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "t-caas-rbac-generator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end -}}

