{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "t-caas-rbac-generator.fullname" . }}
  labels:
{{ include "t-caas-rbac-generator.labels.standard" . | indent 4 }}
rules:
{{ toYaml .Values.rbac.rules | indent 2 }}
{{- end -}}
