apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "t-caas-rbac-generator.fullname" . }}-leader-election
  labels:
{{ include "t-caas-rbac-generator.labels.standard" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "t-caas-rbac-generator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ template "t-caas-rbac-generator.serviceAccountName" .}}
  namespace: {{ .Release.Namespace }}
