{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "t-caas-rbac-generator.serviceAccountName" .}}
  labels:
{{ include "t-caas-rbac-generator.labels.standard" . | indent 4 }}
{{- end }}
