{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "t-caas-rbac-generator.fullname" . }}
  annotations:
    caas.pan-net.eu/job: rbac-generator
    caas.pan-net.eu/scrape: "true"
  labels:
{{ include "t-caas-rbac-generator.labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  selector:
{{ include "t-caas-rbac-generator.labels.standard" . | indent 4 }}
  ports:
  - name: http-metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
{{- end -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "t-caas-rbac-generator.fullname" . }}-webhook
  labels:
{{ include "t-caas-rbac-generator.labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  selector:
{{ include "t-caas-rbac-generator.labels.standard" . | indent 4 }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
