{{- range $index, $authBackend := .Values.global.cluster.authBackends }}
---
apiVersion: authorization.t-caas.telekom.com/v1alpha1
kind: BindDefinition
metadata:
  name: {{ $authBackend.name }}-bd-platform-namespaced-reader-restricted
spec:
  targetName: {{ $authBackend.name }}-bd-platform-ns-reader-restricted
  subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%splatform_namespaced_reader" $authBackend.oidcGroupNamePrefix) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%splatform_namespaced_collaborator" $authBackend.oidcGroupNamePrefix) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%splatform_namespaced_poweruser" $authBackend.oidcGroupNamePrefix) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%splatform_cluster_reader" $authBackend.oidcGroupNamePrefix) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%splatform_cluster_collaborator" $authBackend.oidcGroupNamePrefix) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%splatform_cluster_poweruser" $authBackend.oidcGroupNamePrefix) $authBackend.oidcGroupNameDelimiter }}
    - kind: ServiceAccount
      namespace: kube-system
      name: m2m-sa-t-caas-platform
  roleBindings:
    clusterRoleRefs:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole 
      name: t-caas-platform-namespaced-reader-restricted
    namespaceSelector:
    - matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - kube-public
          - kube-node-lease
      - key: t-caas.telekom.com/owner
        operator: NotIn
        values:
          - platform
    - matchExpressions:
      - key: t-caas.telekom.com/owner
        operator: In 
        values:
          - tenant 
    - matchExpressions:
      - key: t-caas.telekom.com/owner
        operator: In 
        values:
          - thirdparty
{{- end }}
