{{- range $index, $authBackend := .Values.global.cluster.authBackends }}
---
apiVersion: authorization.t-caas.telekom.com/v1alpha1
kind: BindDefinition
metadata:
  name: {{ $authBackend.name }}-bd-platform-cluster-poweruser
spec:
  targetName: {{ $authBackend.name }}-bd-platform-cl-poweruser
  subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ (printf "oidc:%splatform_cluster_poweruser" $authBackend.oidcGroupNamePrefix) | replace "_" $authBackend.oidcGroupNameDelimiter }}
    - kind: ServiceAccount
      namespace: kube-system
      name: m2m-sa-t-caas-platform
  clusterRoleBindings:
    clusterRoleRefs:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole 
      name: t-caas-platform-cluster-poweruser
{{- end }}
