{{- $enforceAutomationGlobal := default "false" $.Values.global.enforceAutomationGlobal }}
{{- $enforceAutomationCluster := $.Values.global.enforceAutomationCluster | default "" }}
{{- $enforceAutomation := $enforceAutomationGlobal }}
{{- if ne $enforceAutomationCluster "" }}
  {{- $enforceAutomation = $enforceAutomationCluster }}
{{- end }}
{{- range $index, $authBackend := .Values.global.cluster.authBackends }}
---
apiVersion: authorization.t-caas.telekom.com/v1alpha1
kind: BindDefinition
metadata:
  name: {{ $authBackend.name }}-bd-tenant-cluster-reader
spec:
  targetName: {{ $authBackend.name }}-bd-tenant-cl-reader
  subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_cluster_reader" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_cluster_reader" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_%s_%s_cluster_reader" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.name $.Values.global.cluster.tenant $.Values.global.cluster.location $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    {{- if eq $enforceAutomation "false" }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_cluster_collaborator" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_cluster_poweruser" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_cluster_collaborator" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_cluster_poweruser" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_%s_%s_cluster_collaborator" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.name $.Values.global.cluster.tenant $.Values.global.cluster.location $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_%s_%s_cluster_poweruser" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.name $.Values.global.cluster.tenant $.Values.global.cluster.location $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    {{- else }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_m2m_cluster_reader" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_m2m_cluster_collaborator" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_m2m_cluster_poweruser" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_m2m_cluster_reader" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_m2m_cluster_collaborator" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_m2m_cluster_poweruser" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.tenant $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_%s_%s_m2m_cluster_reader" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.name $.Values.global.cluster.tenant $.Values.global.cluster.location $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_%s_%s_m2m_cluster_collaborator" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.name $.Values.global.cluster.tenant $.Values.global.cluster.location $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%s%s_%s_%s_%s_m2m_cluster_poweruser" $authBackend.oidcGroupNamePrefix $.Values.global.cluster.name $.Values.global.cluster.tenant $.Values.global.cluster.location $.Values.global.cluster.environment) $authBackend.oidcGroupNameDelimiter }}
    {{- end }}
    - kind: ServiceAccount
      namespace: kube-system
      name: m2m-sa-t-caas-{{ $.Values.global.cluster.tenant }}
  clusterRoleBindings:
    clusterRoleRefs:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole 
      name: t-caas-tenant-cluster-reader
{{- end }}
