{{- if .Values.idp.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: idp-{{ template "authn-authz-operator.fullname" . }}
  labels:
{{ include "authn-authz-operator.labels.idp" . | indent 4 }}
rules:
{{ toYaml .Values.idp.rbac.rules | indent 2 }}
{{- end -}}
