apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: idp-{{ template "authn-authz-operator.fullname" . }}
  labels:
{{ include "authn-authz-operator.labels.idp" . | indent 4 }}
{{- if .Values.idp.annotations }}
  annotations:
{{ toYaml .Values.idp.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
{{ include "authn-authz-operator.labels.idp" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "authn-authz-operator.labels.idp" . | indent 8 }}
      {{- if .Values.idp.annotations }}
      annotations:
{{ toYaml .Values.idp.annotations | indent 8 }}
      {{- end }}
    spec:
      affinity:
{{- toYaml .Values.global.affinity | nindent 8 }}
      securityContext:
        runAsNonRoot: true
      priorityClassName: {{ .Values.global.priorityClassName }}
      imagePullSecrets:
{{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- if .Values.global.serviceAccount.create }}
      serviceAccount: idp-{{ template "authn-authz-operator.serviceAccountName" .}}
      {{- end }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 6 }}
      containers:
      - name: idp
        command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=:8080
          - --function=idp 
        image: {{ include "caas-image-template" .Values.global.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        resources:
{{ toYaml .Values.idp.resources | indent 12 }}
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
          - name: health-probe
            containerPort: 8081
            protocol: TCP 
          - name: metrics 
            containerPort: 8080 
            protocol: TCP
