{{- $firstLineGlobal := default "false" $.Values.global.firstLineGlobal }}
{{- $firstLineCluster := $.Values.global.firstLineCluster | default "" }}
{{- $firstLine := $firstLineGlobal }}
{{- if ne $firstLineCluster "" }}
  {{- $firstLine = $firstLineCluster }}
{{- end }}
{{- if eq $firstLine "true" }}
{{- range $index, $authBackend := .Values.global.cluster.authBackends }}
---
apiVersion: authorization.t-caas.telekom.com/v1alpha1
kind: BindDefinition
metadata:
  name: {{ $authBackend.name }}-bd-firstline-cluster-poweruser
spec:
  targetName: {{ $authBackend.name }}-bd-firstline-cl-poweruser
  subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: Group 
      name: {{ regexReplaceAll "[-_]" (printf "oidc:%sfirstline_cluster_poweruser" $authBackend.oidcGroupNamePrefix) $authBackend.oidcGroupNameDelimiter }}
    - kind: ServiceAccount
      namespace: kube-system
      name: m2m-sa-t-caas-firstline
  clusterRoleBindings:
    clusterRoleRefs:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole 
      name: t-caas-firstline-cluster-poweruser
{{- end }}
{{- end }}
