# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
## Append samples of your project ##
resources:
  - authorization_v1alpha1_roledefinition.yaml
  - authorization_v1alpha1_binddefinition.yaml
  - authorization_v1alpha1_webhookauthorizer.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
