## Append samples of your project ##
resources:
- authorization_v1alpha1_roledefinition.yaml
- authorization_v1alpha1_binddefinition.yaml
- authorization_v1alpha1_webhookauthorizer.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
