{{- if .Values.oidc.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-{{ template "authn-authz-operator.fullname" . }}
  labels:
{{ include "authn-authz-operator.labels.oidc" . | indent 4 }}
rules:
{{ toYaml .Values.oidc.rbac.rules | indent 2 }}
{{- end -}}
