{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-{{ template "authn-authz-operator.serviceAccountName" .}}
  labels:
{{ include "authn-authz-operator.labels.oidc" . | indent 4 }}
{{- end }}
