{{- if .Values.binder.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binder-{{ template "authn-authz-operator.fullname" . }}
  labels:
{{ include "authn-authz-operator.labels.binder" . | indent 4 }}
subjects:
{{- if .Values.global.serviceAccount.create }}
  - kind: ServiceAccount
    name: binder-{{ template "authn-authz-operator.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: binder-{{ template "authn-authz-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end -}}

