{{- if .Values.binder.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: binder-{{ template "authn-authz-operator.fullname" . }}
  labels:
{{ include "authn-authz-operator.labels.binder" . | indent 4 }}
rules:
{{ toYaml .Values.binder.rbac.rules | indent 2 }}
{{- end -}}
