{{- if .Values.binder.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binder-{{ template "authn-authz-operator.fullname" . }}-leader-election
  labels:
{{ include "authn-authz-operator.labels.binder" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: binder-{{ template "authn-authz-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: binder-{{ template "authn-authz-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
