---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: roledefinitions.authorization.t-caas.telekom.com
spec:
  group: authorization.t-caas.telekom.com
  names:
    kind: RoleDefinition
    listKind: RoleDefinitionList
    plural: roledefinitions
    shortNames:
    - roledef
    singular: roledefinition
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Time duration since creation of this RoleDefinition
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Kubernetes API target RBAC object - can be ClusterRole or Role
      jsonPath: .spec.targetRole
      name: Target
      type: string
    - description: The name of the child object created by this RoleDefinition
      jsonPath: .spec.targetName
      name: Role name
      type: string
    - description: The boolean value signifying whether this RoleDefinition is reconciling
        Cluster scoped resources or Namespace scoped resources
      jsonPath: .spec.scopeNamespaced
      name: Namespaced scope
      type: boolean
    - description: The boolean value signifying if the target role has been reconciled
        or not
      jsonPath: .status.roleReconciled
      name: Reconciled role
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RoleDefinition is the Schema for the roledefinitions API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: RoleDefinitionSpec defines the desired state of RoleDefinition
            properties:
              restrictedApis:
                description: |-
                  The restricted APIs field holds all API groups which will *NOT* be reconciled into the "TargetRole"
                  The RBAC operator discovers all API groups available and removes those which are defined by "RestrictedAPIs"
                items:
                  description: |-
                    APIGroup contains the name, the supported versions, and the preferred version
                    of a group.
                  properties:
                    apiVersion:
                      description: |-
                        APIVersion defines the versioned schema of this representation of an object.
                        Servers should convert recognized schemas to the latest internal value, and
                        may reject unrecognized values.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                      type: string
                    kind:
                      description: |-
                        Kind is a string value representing the REST resource this object represents.
                        Servers may infer this from the endpoint the client submits requests to.
                        Cannot be updated.
                        In CamelCase.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                      type: string
                    name:
                      description: name is the name of the group.
                      type: string
                    preferredVersion:
                      description: |-
                        preferredVersion is the version preferred by the API server, which
                        probably is the storage version.
                      properties:
                        groupVersion:
                          description: groupVersion specifies the API group and version
                            in the form "group/version"
                          type: string
                        version:
                          description: |-
                            version specifies the version in the form of "version". This is to save
                            the clients the trouble of splitting the GroupVersion.
                          type: string
                      required:
                      - groupVersion
                      - version
                      type: object
                    serverAddressByClientCIDRs:
                      description: |-
                        a map of client CIDR to server address that is serving this group.
                        This is to help clients reach servers in the most network-efficient way possible.
                        Clients can use the appropriate server address as per the CIDR that they match.
                        In case of multiple matches, clients should use the longest matching CIDR.
                        The server returns only those CIDRs that it thinks that the client can match.
                        For example: the master will return an internal IP CIDR only, if the client reaches the server using an internal IP.
                        Server looks at X-Forwarded-For header or X-Real-Ip header or request.RemoteAddr (in that order) to get the client IP.
                      items:
                        description: ServerAddressByClientCIDR helps the client to
                          determine the server address that they should use, depending
                          on the clientCIDR that they match.
                        properties:
                          clientCIDR:
                            description: The CIDR with which clients can match their
                              IP to figure out the server address that they should
                              use.
                            type: string
                          serverAddress:
                            description: |-
                              Address of this server, suitable for a client that matches the above CIDR.
                              This can be a hostname, hostname:port, IP or IP:port.
                            type: string
                        required:
                        - clientCIDR
                        - serverAddress
                        type: object
                      type: array
                      x-kubernetes-list-type: atomic
                    versions:
                      description: versions are the versions supported in this group.
                      items:
                        description: |-
                          GroupVersion contains the "group/version" and "version" string of a version.
                          It is made a struct to keep extensibility.
                        properties:
                          groupVersion:
                            description: groupVersion specifies the API group and
                              version in the form "group/version"
                            type: string
                          version:
                            description: |-
                              version specifies the version in the form of "version". This is to save
                              the clients the trouble of splitting the GroupVersion.
                            type: string
                        required:
                        - groupVersion
                        - version
                        type: object
                      type: array
                      x-kubernetes-list-type: atomic
                  required:
                  - name
                  - versions
                  type: object
                type: array
              restrictedResources:
                description: |-
                  The restricted resources field holds all resources which will *NOT* be reconciled into the "TargetRole"
                  The RBAC operator discovers all API resources available and removes those which are defined by "RestrictedResources"
                items:
                  description: APIResource specifies the name of a resource and whether
                    it is namespaced.
                  properties:
                    categories:
                      description: categories is a list of the grouped resources this
                        resource belongs to (e.g. 'all')
                      items:
                        type: string
                      type: array
                      x-kubernetes-list-type: atomic
                    group:
                      description: |-
                        group is the preferred group of the resource.  Empty implies the group of the containing resource list.
                        For subresources, this may have a different value, for example: Scale".
                      type: string
                    kind:
                      description: kind is the kind for the resource (e.g. 'Foo' is
                        the kind for a resource 'foo')
                      type: string
                    name:
                      description: name is the plural name of the resource.
                      type: string
                    namespaced:
                      description: namespaced indicates if a resource is namespaced
                        or not.
                      type: boolean
                    shortNames:
                      description: shortNames is a list of suggested short names of
                        the resource.
                      items:
                        type: string
                      type: array
                      x-kubernetes-list-type: atomic
                    singularName:
                      description: |-
                        singularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely.
                        The singularName is more correct for reporting status on a single item and both singular and plural are allowed
                        from the kubectl CLI interface.
                      type: string
                    storageVersionHash:
                      description: |-
                        The hash value of the storage version, the version this resource is
                        converted to when written to the data store. Value must be treated
                        as opaque by clients. Only equality comparison on the value is valid.
                        This is an alpha feature and may change or be removed in the future.
                        The field is populated by the apiserver only if the
                        StorageVersionHash feature gate is enabled.
                        This field will remain optional even if it graduates.
                      type: string
                    verbs:
                      description: |-
                        verbs is a list of supported kube verbs (this includes get, list, watch, create,
                        update, patch, delete, deletecollection, and proxy)
                      items:
                        type: string
                      type: array
                    version:
                      description: |-
                        version is the preferred version of the resource.  Empty implies the version of the containing resource list
                        For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource's group)".
                      type: string
                  required:
                  - kind
                  - name
                  - namespaced
                  - singularName
                  - verbs
                  type: object
                type: array
              restrictedVerbs:
                description: |-
                  The restricted verbs field holds all verbs which will *NOT* be reconciled into the "TargetRole"
                  The RBAC operator discovers all resource verbs available and removes those which are defined by "RestrictedVerbs"
                items:
                  type: string
                type: array
              scopeNamespaced:
                description: |-
                  The scope controls whether the API resource is namespaced or not. This can also be checked by
                  running `kubectl api-resources --namespaced=true/false`
                type: boolean
              targetName:
                description: The name of the target role. This can be any name that
                  accurately describes the ClusterRole/Role
                minLength: 5
                type: string
              targetNamespace:
                description: The target namespace for the Role. This value is necessary
                  when the "TargetRole" is "Role"
                type: string
              targetRole:
                description: The target role that will be reconciled. This can be
                  a ClusterRole or a namespaced Role
                enum:
                - ClusterRole
                - Role
                type: string
            required:
            - scopeNamespaced
            - targetName
            - targetRole
            type: object
          status:
            description: RoleDefinitionStatus defines the observed state of RoleDefinition
            properties:
              conditions:
                description: Conditions defines current service state of the Role
                  definition. All conditions should evaluate to true to signify successful
                  reconciliation.
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource.\n---\nThis struct is intended for
                    direct use as an array at the field path .status.conditions.  For
                    example,\n\n\n\ttype FooStatus struct{\n\t    // Represents the
                    observations of a foo's current state.\n\t    // Known .status.conditions.type
                    are: \"Available\", \"Progressing\", and \"Degraded\"\n\t    //
                    +patchMergeKey=type\n\t    // +patchStrategy=merge\n\t    // +listType=map\n\t
                    \   // +listMapKey=type\n\t    Conditions []metav1.Condition `json:\"conditions,omitempty\"
                    patchStrategy:\"merge\" patchMergeKey:\"type\" protobuf:\"bytes,1,rep,name=conditions\"`\n\n\n\t
                    \   // other fields\n\t}"
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: |-
                        type of condition in CamelCase or in foo.example.com/CamelCase.
                        ---
                        Many .condition.type values are consistent across resources like Available, but because arbitrary conditions can be
                        useful (see .node.status.conditions), the ability to deconflict is important.
                        The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              roleReconciled:
                description: Not extremely important as most status updates are driven
                  by Conditions. We read the JSONPath from this status field to signify
                  completed reconciliation.
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
