---
apiVersion: v2
name: t-caas-rbac-generator
version: 0.1.1
appVersion: "0.1.1"
kubeVersion: ">=1.25.0-0"
description: Generates ClusterRoles and Roles
type: application
keywords:
  - rbac
  - policy
  - authN
  - authZ
  - authentication
  - authorization
  - ClusterRoles
  - Roles 
  - OIDC
home: https://gitlab.devops.telekom.de/tdi-caas/helm-charts/t-caas-rbac-generator
maintainers:
  - name: T-CaaS Platform Team
deprecated: False

