{{- if .Values.generator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: generator-{{ template "authn-authz-operator.fullname" . }}-leader-election
  labels:
{{ include "authn-authz-operator.labels.generator" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generator-{{ template "authn-authz-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: generator-{{ template "authn-authz-operator.serviceAccountName" .}}
  namespace: {{ .Release.Namespace }}
{{- end -}}
