{{- if .Values.generator.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: generator-authn-authz-metrics
  annotations:
    caas.pan-net.eu/job: generator-authn-authz
    caas.pan-net.eu/scrape: "true"
  labels:
{{ include "authn-authz-operator.labels.generator" . | indent 4 }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  selector:
{{ include "authn-authz-operator.labels.generator" . | indent 4 }}
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: generator-authn-authz-webhook
  labels:
{{ include "authn-authz-operator.labels.generator" . | indent 4 }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  selector:
{{ include "authn-authz-operator.labels.generator" . | indent 4 }}
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
