{{- $name := printf "generator-authn-authz-webhook" }}
{{- $namespacedName := printf "generator-authn-authz-webhook.%s" .Release.Namespace }}
{{- $cn := printf "generator-authn-authz-webhook.%s.svc" .Release.Namespace }}
{{- $ca := genCA "authn-authz-webhook-ca" 3650 -}}
{{- $cert := genSignedCert $cn nil (list $name $namespacedName $cn ) 3650 $ca -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: generator-{{ template "authn-authz-operator.fullname" . }}-validating-webhook
  labels:
{{ include "authn-authz-operator.labels.generator" . | indent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: generator-authn-authz-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-authorization-t-caas-telekom-com-v1alpha1-roledefinition
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validating.webhook.authn-authz.t-caas.telekom.de
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - authorization.t-caas.telekom.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - roledefinitions
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: v1
kind: Secret
metadata:
  name: generator-{{ template "authn-authz-operator.fullname" . }}-webhook-cert
  labels:
{{ include "authn-authz-operator.labels.generator" . | indent 4 }}
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
